Update dashboard with correct IP address
atlassian-labs/Confluence-DC-Grafana-Dashboards pull request #1
Opened 2022-03-20 22:44 UTC by bcarnevale

2022-03-20 22:47 UTC, atl-mk commented
I'm not sure if the PR title is correct, I see other changes. Also the IP address won't help customers.

2022-03-20 22:47 UTC, atl-mk approved these changes

2022-03-20 22:50 UTC, Wil312 commented
I think we should wait until we've labelled the relevant metrics with a `product` (we'll be removing the hardcoded IPs as these are specific to our environments)

2022-03-21 05:33 UTC, amcculloch2 approved these changes

2022-03-21 06:01 UTC, Wil312 commented on Overview.json
> +          "expr": "increase(java_lang_G1_Old_Generation_CollectionTime[10m])",
This needs `{product="confluence"}`

2022-03-21 06:01 UTC, Wil312 commented on Overview.json
> +          "expr": "increase(java_lang_G1_Young_Generation_CollectionTime[10m])",
This needs {product="confluence"}

2022-03-21 06:02 UTC, Wil312 commented on Overview.json
> +          "expr": "increase(java_lang_G1_Old_Generation_CollectionCount[10m])",
This needs {product="confluence"}

2022-03-21 06:02 UTC, Wil312 commented on Overview.json
> +          "expr": "increase(java_lang_G1_Young_Generation_CollectionCount[10m])",
This needs {product="confluence"}

2022-03-21 06:03 UTC, Wil312 requested changes
Please see 4 comments left

2022-03-21 06:13 UTC, Wil312 approved these changes

2022-03-21 22:06 UTC, merged